import csv
import logging
import os
import re
from typing import Set

from poursuite.config import PROCESS_NUMBER_PATTERN

logger = logging.getLogger("poursuite.csv_extractor")


class CSVProcessExtractor:
    """Extracts process numbers from CSV files generated by the search engine."""

    def __init__(self):
        self.process_number_pattern = PROCESS_NUMBER_PATTERN

    def extract_from_csv(self, csv_path: str) -> Set[str]:
        """Extract unique process numbers from a CSV file."""
        if not os.path.exists(csv_path):
            raise FileNotFoundError(f"CSV file not found: {csv_path}")

        logger.info(f"Extracting process numbers from: {csv_path}")
        process_numbers = set()

        try:
            csv.field_size_limit(2000000000)

            # Find the header line index
            header_line_idx = 0
            with open(csv_path, 'r', encoding='utf-8-sig', errors='replace') as file:
                for idx, line in enumerate(file):
                    if 'Process Number' in line:
                        header_line_idx = idx
                        break

            # Read the CSV part, skipping the summary section
            with open(csv_path, 'r', encoding='utf-8-sig', errors='replace') as file:
                for _ in range(header_line_idx):
                    next(file)

                reader = csv.reader(file)
                header = next(reader)

                process_col_idx = None
                for idx, col_name in enumerate(header):
                    if 'Process Number' in col_name:
                        process_col_idx = idx
                        break

                if process_col_idx is None:
                    raise ValueError("Could not find 'Process Number' column in the CSV file")

                row_count = 0
                for row in reader:
                    row_count += 1
                    if len(row) > process_col_idx:
                        cell_value = row[process_col_idx]
                        matches = re.findall(self.process_number_pattern, cell_value)
                        for match in matches:
                            process_numbers.add(match)

                logger.info(f"Processed {row_count} rows, found {len(process_numbers)} unique process numbers")

        except Exception as e:
            logger.error(f"Error extracting process numbers: {e}")
            self._extract_with_fallback(csv_path, process_numbers)

        return process_numbers

    def _extract_with_fallback(self, csv_path: str, process_numbers: Set[str]) -> None:
        """Fallback: scan entire file content for process number patterns."""
        logger.info("Using fallback extraction method...")
        try:
            with open(csv_path, 'r', encoding='utf-8-sig', errors='replace') as file:
                content = file.read()
                matches = re.findall(self.process_number_pattern, content)
                for match in matches:
                    process_numbers.add(match)
            logger.info(f"Fallback method found {len(process_numbers)} unique process numbers")
        except Exception as e:
            logger.error(f"Fallback extraction also failed: {e}")
